"""libros con multa

Revision ID: ceb4f2ffa0d2
Revises: d39eb092bb72
Create Date: 2023-12-04 10:54:17.944180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb4f2ffa0d2'
down_revision: Union[str, None] = 'd39eb092bb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('fine', sa.Integer(), nullable=False, server_default='1000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'fine')
    # ### end Alembic commands ###
