"""prestamos sin BookClient

Revision ID: d39eb092bb72
Revises: a8a44353e3e9
Create Date: 2023-12-03 22:26:53.972880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39eb092bb72'
down_revision: Union[str, None] = 'a8a44353e3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_clients',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='books_clients_book_id_fkey'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='books_clients_client_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'client_id', name='books_clients_pkey')
    )
    # ### end Alembic commands ###
